// Code generated by "stringer -type=BucketId"; DO NOT EDIT.

package cards

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DefaultBucket-0]
	_ = x[BucketA-1]
	_ = x[BucketB-2]
	_ = x[ArchiveBucket-254]
	_ = x[DoneBucket-255]
}

const (
	_BucketId_name_0 = "DefaultBucketBucketABucketB"
	_BucketId_name_1 = "ArchiveBucketDoneBucket"
)

var (
	_BucketId_index_0 = [...]uint8{0, 13, 20, 27}
	_BucketId_index_1 = [...]uint8{0, 13, 23}
)

func (i BucketId) String() string {
	switch {
	case i <= 2:
		return _BucketId_name_0[_BucketId_index_0[i]:_BucketId_index_0[i+1]]
	case 254 <= i && i <= 255:
		i -= 254
		return _BucketId_name_1[_BucketId_index_1[i]:_BucketId_index_1[i+1]]
	default:
		return "BucketId(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
